<?php

class AdminSubNavigationsTableSeeder extends Seeder {

	public function run() {
		// Uncomment the below to wipe the table clean before populating
		// DB::table('settings')->truncate();

		DB::table('admin_subnavigations') -> insert(array( 
											array('admin_navigation_id' => 3, 
												'title' => 'Navigation group', 
												'url' => 'navigationgroups', 
												'order' => 1,
												'created_at' => new DateTime, 
												'updated_at' => new DateTime,), 
											array('admin_navigation_id' => 3, 
												'title' => 'Pages', 
												'url' => 'pages', 
												'order' => 2,
												'created_at' => new DateTime, 
												'updated_at' => new DateTime,), 
											array('admin_navigation_id' => 3, 
												'title' => 'Navigation', 
												'url' => 'navigation', 
												'order' => 3,
												'created_at' => new DateTime, 
												'updated_at' => new DateTime,), 
											array('admin_navigation_id' => 4, 
												'title' => 'Blog categorys', 
												'url' => 'blogcategorys', 
												'order' => 1,
												'created_at' => new DateTime, 
												'updated_at' => new DateTime,), 
											array('admin_navigation_id' => 4, 
												'title' => 'Blog', 
												'url' => 'blogs', 
												'order' => 2,
												'created_at' => new DateTime, 
												'updated_at' => new DateTime,), 
											array('admin_navigation_id' => 4, 
												'title' => 'Blog comments', 
												'url' => 'blogcomments', 
												'order' => 3,
												'created_at' => new DateTime, 
												'updated_at' => new DateTime,), 
											array('admin_navigation_id' => 4, 
												'title' => 'Gallery images', 
												'url' => 'galleryimages', 
												'order' => 1,
												'created_at' => new DateTime, 
												'updated_at' => new DateTime,), 
											array('admin_navigation_id' => 4, 
												'title' => 'Galleries', 
												'url' => 'galleries', 
												'order' => 2,
												'created_at' => new DateTime, 
												'updated_at' => new DateTime,), 
											array('admin_navigation_id' => 4, 
												'title' => 'Gallery comments', 
												'url' => 'galleryimagecomments', 
												'order' => 3,
												'created_at' => new DateTime, 
												'updated_at' => new DateTime,), 											
											array('admin_navigation_id'=> 6, 
												'title' => 'Users', 
												'url' => 'users', 
												'order' => 1,
												'created_at' => new DateTime, 
												'updated_at' => new DateTime,), 
											array('admin_navigation_id' => 6, 
												'title' => 'Roles', 
												'url' => 'roles', 
												'order' => 2,
												'created_at' => new DateTime, 
												'updated_at' => new DateTime,),
										)
									);

	}

}
